<?xml version="1.0" encoding="utf-8"?><Database Name="DNN_StructuredContent" EntityNamespace="StructuredContent.DAL" ContextNamespace="StructuredContent.DAL" Class="DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.StructuredContent_ContentField" Member="StructuredContent_ContentFields">
    <Type Name="StructuredContent_ContentField">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ContentTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsSystem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Ordinal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ColumnName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="DataType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataLength" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AllowNull" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DefaultValue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HelpText" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ContentFieldTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Options" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LayoutRow" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LayoutColumn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="StructuredContent_ContentFieldType_StructuredContent_ContentField" Member="StructuredContent_ContentFieldType" ThisKey="ContentFieldTypeId" OtherKey="Id" Type="StructuredContent_ContentFieldType" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="StructuredContent_ContentType_StructuredContent_ContentField" Member="StructuredContent_ContentType" ThisKey="ContentTypeId" OtherKey="Id" Type="StructuredContent_ContentType" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StructuredContent_VisualizerTemplate" Member="StructuredContent_VisualizerTemplates">
    <Type Name="StructuredContent_VisualizerTemplate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContentTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Script" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Css" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Template" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Language" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ContentSize" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="StructuredContent_VisualizerTemplate_StructuredContent_Visualizer" Member="StructuredContent_Visualizers" ThisKey="Id" OtherKey="VisualizerTemplateId" Type="StructuredContent_Visualizer" />
      <Association Name="StructuredContent_ContentType_StructuredContent_VisualizerTemplate" Member="StructuredContent_ContentType" ThisKey="ContentTypeId" OtherKey="Id" Type="StructuredContent_ContentType" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StructuredContent_ContentFieldType" Member="StructuredContent_ContentFieldTypes">
    <Type Name="StructuredContent_ContentFieldType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ordinal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DefaultDataType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DefaultDataLength" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DefaultOptions" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Icon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="StructuredContent_ContentFieldType_StructuredContent_ContentField" Member="StructuredContent_ContentFields" ThisKey="Id" OtherKey="ContentFieldTypeId" Type="StructuredContent_ContentField" />
    </Type>
  </Table>
  <Table Name="dbo.StructuredContent_ContentType" Member="StructuredContent_ContentTypes">
    <Type Name="StructuredContent_ContentType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Singular" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Plural" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="UrlSlug" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="TableName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="IsSystem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="StructuredContent_ContentType_StructuredContent_ContentField" Member="StructuredContent_ContentFields" ThisKey="Id" OtherKey="ContentTypeId" Type="StructuredContent_ContentField" />
      <Association Name="StructuredContent_ContentType_StructuredContent_VisualizerTemplate" Member="StructuredContent_VisualizerTemplates" ThisKey="Id" OtherKey="ContentTypeId" Type="StructuredContent_VisualizerTemplate" />
      <Association Name="StructuredContent_ContentType_StructuredContent_Relationship" Member="StructuredContent_Relationships" ThisKey="Id" OtherKey="AContentTypeId" Type="StructuredContent_Relationship" />
      <Association Name="StructuredContent_ContentType_StructuredContent_Relationship1" Member="StructuredContent_Relationships1" ThisKey="Id" OtherKey="BContentTypeId" Type="StructuredContent_Relationship" />
      <Association Name="StructuredContent_ContentType_StructuredContent_Revision" Member="StructuredContent_Revisions" ThisKey="Id" OtherKey="ContentTypeId" Type="StructuredContent_Revision" />
      <Association Name="StructuredContent_ContentType_StructuredContent_Visualizer" Member="StructuredContent_Visualizers" ThisKey="Id" OtherKey="ContentTypeId" Type="StructuredContent_Visualizer" />
    </Type>
  </Table>
  <Table Name="dbo.StructuredContent_Relationship" Member="StructuredContent_Relationships">
    <Type Name="StructuredContent_Relationship">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="AContentTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BContentTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ARequired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AMinLimit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AMaxLimit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AHelpText" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="BRequired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BMinLimit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BMaxLimit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BHelpText" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ALayoutRow" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ALayoutColumn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BLayoutRow" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BLayoutColumn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="StructuredContent_ContentType_StructuredContent_Relationship" Member="StructuredContent_ContentType" ThisKey="AContentTypeId" OtherKey="Id" Type="StructuredContent_ContentType" IsForeignKey="true" />
      <Association Name="StructuredContent_ContentType_StructuredContent_Relationship1" Member="StructuredContent_ContentType1" ThisKey="BContentTypeId" OtherKey="Id" Type="StructuredContent_ContentType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StructuredContent_Revision" Member="StructuredContent_Revisions">
    <Type Name="StructuredContent_Revision">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RevisionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActivityType" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ContentTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Delta" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="StructuredContent_ContentType_StructuredContent_Revision" Member="StructuredContent_ContentType" ThisKey="ContentTypeId" OtherKey="Id" Type="StructuredContent_ContentType" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StructuredContent_Visualizer" Member="StructuredContent_Visualizers">
    <Type Name="StructuredContent_Visualizer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ModuleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContentTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VisualizerTemplateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemFilter" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="StructuredContent_ContentType_StructuredContent_Visualizer" Member="StructuredContent_ContentType" ThisKey="ContentTypeId" OtherKey="Id" Type="StructuredContent_ContentType" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="StructuredContent_VisualizerTemplate_StructuredContent_Visualizer" Member="StructuredContent_VisualizerTemplate" ThisKey="VisualizerTemplateId" OtherKey="Id" Type="StructuredContent_VisualizerTemplate" IsForeignKey="true" />
    </Type>
  </Table>
</Database>