name: Build

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'release/**'
  pull_request:
    branches:
      - main
      - master
      - develop
      - 'release/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow
      - name: Run './build.sh'
        run: ./build.sh --github-token $GITHUB_TOKEN --target CI
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: artifacts/*
